### ISSUE TITLE
Location search should be sorted

### ISSUE THREAD

**Issue by JoeCohen** [MushroomObserver/mushroom-observer-mobile#19]
This would make it easier for a user to select the best Location when the user's desired Location does not exist.
Ex:
- I wanted to use a Location that doesn't yet exist, Chehalem Ridge Nature Park.
- I know it's in Washington County Oregon
- I type `Washington Co., Or". (That's sufficient to limit the results to the region Washington Co., Oregon, USA.)
Desired result: Hits are displayed in alpha order
Actual result: They are not in alpha order. (I can't tell how they are ordered.)

Question for @pellaea or @oliviacpu: In what order are they provided by the webserver script? Maybe that's the right place to handle this?

**Comment by pellaea** [comment]
Are you talking about auto-complete, or the location search function, Joe?

**Comment by JoeCohen** [comment]
![IMG_2180](https://user-images.githubusercontent.com/45460/152225359-f7293511-7d5d-446e-9c66-9b1a33596381.jpeg)
![IMG_2178](https://user-images.githubusercontent.com/45460/152225371-ed9c0ebc-0624-403d-8a37-399080bbac46.jpeg)

**Comment by oliviacpu** [comment]
I think I can sort the filtered matches alphabetically from the start of the location name. I'll do that to start.

Sorting the entire list is challenging because we don't really have the actual address components. Trying to parse them ends up with some funky results.

```
[
  {
    id: 214,
    name: 'North Carolina, USA',
    prefix: 'N',
    street: 'Carolina'
  },
  {
    id: 53,
    name: 'Asheville, Buncombe Co., North Carolina, USA',
    street: 'Asheville',
    city: 'Buncombe',
    state: 'Co'
  },
  {
    id: 60,
    name: 'Gray Whale Ranch, Santa Cruz Co., California, USA',
    street: 'Gray Whale',
    type: 'Rnch',
    city: 'Santa Cruz',
    state: 'Co'
  },
  {
    id: 5,
    name: 'Gualala, Mendocino Co., California, USA',
    street: 'Gualala',
    city: 'Mendocino',
    state: 'Co'
  },
  {
    id: 36,
    name: 'Ortega Highway, Cleveland National Forest, California, USA',
    street: 'Ortega',
    type: 'Hwy',
    city: 'Cleveland National Forest',
    state: 'CA'
  },
  {
    id: 58,
    name: 'Santa Cruz, Santa Cruz Co., California, USA',
    street: 'Santa'
  },
  {
    id: 39,
    name: 'Wilder Ridge, Humboldt Co., California, USA',
    street: 'Wilder',
    type: 'Rdg',
    city: 'Humboldt',
    state: 'Co'
  },
  {
    id: 69,
    name: 'Crescenta Valley Community Regional Park, La Crescenta, California, USA',
    street: 'Crescenta Valley Community Regional',
    type: 'Park',
    city: 'La Crescenta',
    state: 'CA'
  },
  {
    id: 38,
    name: 'Chumash Interpretive Center, Thousand Oaks, Ventura Co., California, USA',
    street: 'Chumash Interpretive',
    type: 'Ctr'
  },
  {
    id: 4186,
    name: 'Jackson Demonstration State Forest, Mendocino Co., California, USA',
    street: 'Jackson Demonstration State',
    type: 'Frst',
    city: 'Mendocino',
    state: 'Co'
  }
]
```

**Comment by pellaea** [comment]
Woah!  Where are the extra fields coming from?  That's so cool... and
sometimes random... :)

**Comment by oliviacpu** [comment]
@pellaea They came from a script I ran to test an address parsing library! ID and name are the only things the endpoint returns.

**Comment by JoeCohen** [comment]
That's funny! Made my day.
An alpha sort based on `name` would be great. (And it's also the way the web site works. I thank, but can't double check right now because the site is so sloooooow.)
