### ISSUE TITLE
Saved Draft/Observation should use date selected by user

### ISSUE THREAD

**Issue by JoeCohen** [MushroomObserver/mushroom-observer-mobile#27]
To replicate:
- Create Observation 
- Next
- change the Date, 
- pick a Location
- Save
Expected result: Draft is saved with the Date selected by the user
Actual result: Draft is saved with the current Date

**Comment by mo-nathan** [comment]
@JoeCohen Is this appears to be fixed.  Shall I close it or do you want to verify?

**Comment by mo-nathan** [comment]
Appears to be fixed.
