### ISSUE TITLE
Android should have thumbnail for Observations

### ISSUE THREAD

**Issue by JoeCohen** [MushroomObserver/mushroom-observer-mobile#34]
Per @mo-nathan: 
> The only relatively minor issue I saw is that the observation list would be better if it had a thumbnail.

**Comment by mo-nathan** [comment]
Has this been fixed?  I no longer have an Android to test it.

**Comment by mo-nathan** [comment]
Looked at this in the emulator and the thumbnails are showing up in Android.  Note that the emulator seems to pull images from the website for saved observations.  This raises the question of whether that works when disconnected.
