### ISSUE TITLE
Image corruption in uploads

### ISSUE THREAD

**Issue by oliviacpu** [MushroomObserver/mushroom-observer-mobile#56]
Sometimes observation images show as corrupted after being uploaded from mobile

Add a checksum for the image data to allow the server and app to know they have good data

**Comment by JoeCohen** [comment]
The bug is on the web/imageserver side, not the mobile app side.

**Comment by JoeCohen** [comment]
I am closing this issue because it's not a mobile issue.
(I also think that Jason may have fixed it.)
