### ISSUE TITLE
Manual geolocation entry broken

### ISSUE THREAD

**Issue by JoeCohen** [MushroomObserver/mushroom-observer-mobile#71]
Manual geolocation entry is severely flawed
- There's no way to enter a minus. (So nothing: west of the prime meridian, in the southern hemisphere, or below sea level.)
- lat/lon limited to 5 characters, altitude to 4 characters. (So precision is restricted.)
App Version 1.0.48, iPhone Xr iOS 17.3.1

Comment: Although it's severely flawed it affects almost nobody. I didn't notice the problem until today (2024-02-18) when a user sent an email to webmaster. (See below.) This was the first report of this bug.

>Sun, Feb 18, 2024 at 10:00 AM
Reply-To: markusschoenleitner@web.de
To: webmaster@mushroomobserver.org
I can not type in the coordinates manually in the app. I can only type 5 digits and no dot

Note: I think he just didn't notice the dot. I've emailed him about this.

**Comment by mo-nathan** [comment]
I believe this is fixed by https://github.com/MushroomObserver/mo-mobile/pull/25.
